using System;
using System.Linq;
using System.Threading.Tasks;
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using PavlovRconWebserver.Extensions;
using PavlovRconWebserver.Models;
using PavlovRconWebserver.Services;
using Serilog.Events;

namespace PavlovRconWebserver.Controllers
{
    public class ApiWithKeyController : Controller
    {
        public IToastifyService _notifyService { get; }
        private readonly PavlovServerService _pavlovServerService;
        private readonly SshServerSerivce _sshServerSerivce;
        private readonly UserService _userService;
        private readonly ReservedServersService _reservedServersService;
        private readonly string ApiKey;
        private readonly string GeneratedServerPath;
        
        public ApiWithKeyController(PavlovServerService pavlovServerService,
                                    SshServerSerivce sshServerSerivce,
                                    ReservedServersService reservedServersService,
                                    UserService userService,
                                    IToastifyService notyfService,
                                    IConfiguration configuration)
        {
            _notifyService = notyfService;
            _pavlovServerService = pavlovServerService;
            _sshServerSerivce = sshServerSerivce;
            _userService = userService;
            _reservedServersService = reservedServersService;
            ApiKey = configuration.GetSection("ApiKey").Value;
            GeneratedServerPath = configuration.GetSection("GeneratedServerPath").Value;
        }
        
        [HttpGet("Api/GetListOfAvailable")]
        public async Task<IActionResult> GetListOfAvailable(string apiKey)
        {
            if (!HasAccess(apiKey)) return BadRequest("No Authkey set or wrong auth key!");
            var list = (await _sshServerSerivce.FindAll()).Where(x => x.HostingAvailable).Select(x => new
            {
                x.Id,
                x.Name
            });
            return new ObjectResult(list);
        }


        [HttpGet("Api/CreateServer")]
        public async Task<IActionResult> CreateServer(string apiKey,int sshServerId,bool shack,string email)
        {
            if (!HasAccess(apiKey)) return BadRequest("No AuthKey set or wrong auth key!");
            var sshServer = await _sshServerSerivce.FindOne(sshServerId);
            if (sshServer == null) return BadRequest("The ssh server does not exist!");
            if (!sshServer.HostingAvailable) return BadRequest("The ssh server ist not for hosting!");

            var guid = Guid.NewGuid().ToString();
            var model = new PavlovServerViewModel
            {
                Name = "Autogenerated: "+guid,
                TelnetPort = sshServer.PavlovServers.Max(x=>x.TelnetPort)+1,
                DeletAfter = 7,
                TelnetPassword = Guid.NewGuid().ToString(),
                ServerPort = sshServer.PavlovServers.Max(x=>x.ServerPort)+1,
                ServerFolderPath = GeneratedServerPath+guid+"/",
                ServerSystemdServiceName = "pavlov"+guid.Replace("-",""),
                ServerType = ServerType.Community,
                ServerServiceState = ServerServiceState.disabled,
                SshServer = sshServer,
                AutoBalance = false,
                SaveStats = true,
                Shack = shack,
                sshServerId = sshServer.Id,
                create = true,
                SshUsernameRoot = sshServer.SshUsernameRootForHosting,
                SshPasswordRoot = sshServer.SshPasswordRootForHosting,
                SshKeyFileNameRoot = sshServer.SshKeyFileNameRootForHosting,
                SshPassphraseRoot = sshServer.SshPassphraseRootForHosting
            };

            var user = await _userService.GetUserByEmail(email);
            if (user != null)
            {
                model.LiteDbUserId = user.Id.ToString();
                model.Owner = user;
            }
            var result = await _pavlovServerService.CreatePavlovServer(model);
            model = result.Key;
            if (result.Value != null)
            {
                DataBaseLogger.LogToDatabaseAndResultPlusNotify("Could not create rented server! " + model.Name, LogEventLevel.Fatal, _notifyService);
                return BadRequest();
            }
            
            
            var resultServer = await _pavlovServerService.Upsert(model.toPavlovServer(model));
            if (user==null)
            {
                await _reservedServersService.Add(new ReservedServer() { Email = email, ServerId = resultServer.Id});
            }
            return Ok();
        }

        private bool HasAccess(string apiKey)
        {
            if (apiKey != ApiKey || ApiKey == "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" &&
                ApiKey.Length != 64)
            {
                return false;
            }

            return true;
        }
        
        public static bool ApiKeySet(IConfiguration configurationTmp)
        {
            
            var apiKey = configurationTmp.GetSection("ApiKey").Value;
            if (apiKey == "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" ||
                apiKey.Length < 64)
            {
                return false;
            }

            return true;
        }
    }
}